### ISSUE TITLE
Upgrades to React Modal 3.1.x are causing a few warnings.

### ISSUE THREAD

**Issue by allanhortle** [dxinteractive/react-entity-editor#53]
Updating to React 16 means updating react modal to 3. Didn't hit any breaking changes but I did start getting this error:

```
Warning: react-modal: App element is not defined. 
Please use `Modal.setAppElement(el)` or set `appElement={el}`. 
This is needed so screen readers don't see main content when modal is opened. 
It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.
```

https://github.com/reactjs/react-modal#app-element

You can pass in a DOM id which would make it pretty easy to configure.
Might need to be in entity editor configs? Or you could default to some Goose name?

**Comment by dxinteractive** [comment]
Fixed in `0.12.0`
